### PR TITLE
Added often used arguments

### PR DESCRIPTION
**Pull request by PanderMusubi**

### CODE REVIEW

**Comment by PanderMusubi** [comment]
The two commits are independent of each other. Want te create to different PRs but they got joined automatically.

**Comment by menny** [comment]
This seems good to me
👍 

But I'm not the owner..

**Comment by friesenkiwi** [comment]
But there is a relatively new (actually it came from the old SVN repository) terminal keyboard in the AnySoftKeyboard main pack by default: https://github.com/AnySoftKeyboard/AnySoftKeyboard/blob/master/app/src/main/res/xml/terminal.xml
Maybe you would like to add those often used arguments as well?

**Comment by PanderMusubi** [comment]
@friesenkiwi @menny Under which directory and filename do I add a file with autotext for terminal in AnySoftKeyboard for a PR?

**Comment by menny** [comment]
I see that there are some additions in this repo, like a dictionary with common shell commands

**Comment by menny** [comment]
Maybe we should bring those into ASK?

**Comment by PanderMusubi** [comment]
@menny, discussion with @friesenkiwi at the moment led to additional terminal keyboard. Less than 1% of ASK users will use it. So better not confuse them and keep it additional, like a language pack, but conform and up to date with branding. What do you and @pi3nch think?

**Comment by friesenkiwi** [comment]
I'm fine with having it in the main app as well. As long as it is freely available and easily maintainable, I'm fine with most things. ;)
But @PanderMusubi if you like to move this pack to https://github.com/AnySoftKeyboard/LanguagePack and move&merge the Terminal Keyboard from the ASK main app there as well, why not? :)

**Comment by PanderMusubi** [comment]
@friesenkiwi, in a new branch in LanguagePack?

**Comment by friesenkiwi** [comment]
Yes, I thought so? "Terminal", "SSH", "Console", anything like that?

**Comment by PanderMusubi** [comment]
For future reference, see https://github.com/AnySoftKeyboard/LanguagePack/tree/terminal

**Pull request merged**
